apiVersion: apps/v1
kind: Deployment
metadata:
  name: intranet-portal-deployment
  labels:
    app: intranet-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intranet-portal
  template:
    metadata:
      labels:
        app: intranet-portal
    spec:
      containers:
        - name: intranet-portal
          image: jayakavin2005/intranet-portal:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80